### ISSUE TITLE
Unable to install Py3.11 Linux wheel

### ISSUE THREAD

**Issue by David-OConnor** [oberluz/pycoral#2]
Hi! Thanks for all the work on this fork! This is a follow-up to [this thread](https://github.com/google-coral/pycoral/issues/85#issuecomment-1793768842).

OS: Ubuntu Linux 20.04. Python: 3.11. 

Steps;
  - Download `pycoral-2.13.0-cp310-cp310-linux_x86_64.whl` from [pycoral-2.13.0-cp310-cp310-linux_x86_64.whl](The releases page)
  - `python3.11 -m pip install pycoral-2.13.0-cp310-cp310-linux_x86_64.whl`

Error:
```bash
ERROR: could not find a version that satisfies the requirement tflite-runtime==2.13.0 (from pycoral) (from versions: 2.14.0).
Error: No matching distribution found for tflite-runtime==2.13.0
```

Of note, the official `tflite-runtime` package on Pypi doesn't include this version. So, I'm not sure if the fix is only support 2.14+ on PyCoral for Python3.11, or if you think there's another way. I think the former is fine, but given you were able to build these wheels, I'm curious how. (https://pypi.org/project/tflite-runtime/2.13.0/#files)

I already ran into a similar error when attempting to build wheels from the source code in this repo for both Windows/Py3.11, and Ubuntu/Py3.11.

**Comment by oberluz** [comment]
As stated you need to download and install first: https://github.com/oberluz/pycoral/releases/download/2.13.0/tflite_runtime-2.13.0-cp310-cp310-linux_x86_64.whl

**Comment by oberluz** [comment]
```
$ python --version
Python 3.10.12

$ python3 -m pip install ~/Downloads/tflite_runtime-2.13.0-cp310-cp310-linux_x86_64.whl 
Defaulting to user installation because normal site-packages is not writeable
Processing /home/eyeot-demo/Downloads/tflite_runtime-2.13.0-cp310-cp310-linux_x86_64.whl
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from tflite-runtime==2.13.0) (1.23.3)
Installing collected packages: tflite-runtime
Successfully installed tflite-runtime-2.13.0
                      
$ python3 -m pip install ~/Downloads/pycoral-2.13.0-cp310-cp310-linux_x86_64.whl 
Defaulting to user installation because normal site-packages is not writeable
Processing /home/eyeot-demo/Downloads/pycoral-2.13.0-cp310-cp310-linux_x86_64.whl
Requirement already satisfied: Pillow>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from pycoral==2.13.0) (10.1.0)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from pycoral==2.13.0) (1.23.3)
Requirement already satisfied: tflite-runtime==2.13.0 in /home/eyeot-demo/.local/lib/python3.10/site-packages (from pycoral==2.13.0) (2.13.0)
Installing collected packages: pycoral
Successfully installed pycoral-2.13.0
```

**Comment by David-OConnor** [comment]
Thank you.

`python3.11 -m pip install pycoral-2.13.0-cp310-linux_x86_64.whl`

`ERROR: pycoral-2.13.0-cp310-linux_x86_64.whl is not a supported wheel on this platform`.

**Comment by oberluz** [comment]
Yes, 3.11 is also available, but in your description above you mentioned pycoral-2.13.0-cp310-cp310-linux_x86_64.whl

**Comment by David-OConnor** [comment]
Oops, sorry; typo.

**Comment by oberluz** [comment]
So, where you able to install 3.10 or 3.11?

**Comment by David-OConnor** [comment]
No. I don't have Python 3.10, and 3.11 gives the error described.

**Comment by oberluz** [comment]
Where is that error? seems you deleted it

**Comment by oberluz** [comment]
somthing about unsupported architecture

**Comment by David-OConnor** [comment]
I injected too much confusion here due to the typo in the first post. Let's start fresh, please ignore everything prior to this. I'm on my windows machine now, so was manually transcribing from the ubuntu laptop.

Hi! Thanks for all the work on this fork! This is a follow-up to https://github.com/google-coral/pycoral/issues/85#issuecomment-1793768842.

OS: Ubuntu Linux 20.04. Python: 3.11.

Steps;

    Download pycoral-2.13.0-cp311-cp311-linux_x86_64.whl from [pycoral-2.13.0-cp311-cp311-linux_x86_64.whl](The releases page)
    python3.11 -m pip install pycoral-2.13.0-cp310-cp311-linux_x86_64.whl

Error:

ERROR: could not find a version that satisfies the requirement tflite-runtime==2.13.0 (from pycoral) (from versions: 2.14.0).
Error: No matching distribution found for tflite-runtime==2.13.0

Of note, the official tflite-runtime package on Pypi doesn't include this version. So, I'm not sure if the fix is only support 2.14+ on PyCoral for Python3.11, or if you think there's another way. I think the former is fine, but given you were able to build these wheels, I'm curious how. (https://pypi.org/project/tflite-runtime/2.13.0/#files)

I already ran into a similar error when attempting to build wheels from the source code in this repo for both Windows/Py3.11, and Ubuntu/Py3.11.

**Comment by David-OConnor** [comment]
edit: Oh, wow, you solved it. I missed the manual download the tflite runtime, under `show all assets`. Carry on! Sorry about that.

**Comment by oberluz** [comment]
Yes you always need to install tflite_runtime first and then pycoral, using the same version for both
